export const items = [
  { type: "button", content: "about" },
  { type: "button", content: "account" },
  { type: "button", content: "back" },
  { type: "button", content: "blog" },
  { type: "button", content: "cancel" },
  { type: "button", content: "cart" },
  { type: "button", content: "checkout" },
  { type: "button", content: "confirmation" },
  { type: "button", content: "contact" },
  { type: "button", content: "continue" },
  { type: "button", content: "dashboard" },
  { type: "button", content: "discover" },
  { type: "button", content: "download" },
  { type: "button", content: "explore" },
  { type: "button", content: "faq" },
  { type: "button", content: "features" },
  { type: "button", content: "feedback" },
  { type: "button", content: "get started" },
  { type: "button", content: "help" },
  { type: "button", content: "home" },
  { type: "button", content: "join" },
  { type: "button", content: "learn more" },
  { type: "button", content: "login" },
  { type: "button", content: "menu" },
  { type: "button", content: "next" },
  { type: "button", content: "order" },
  { type: "button", content: "previous" },
  { type: "button", content: "pricing" },
  { type: "button", content: "privacy" },
  { type: "button", content: "products" },
  { type: "button", content: "profile" },
  { type: "button", content: "save" },
  { type: "button", content: "search" },
  { type: "button", content: "services" },
  { type: "button", content: "settings" },
  { type: "button", content: "signup" },
  { type: "button", content: "submit" },
  { type: "button", content: "subscribe" },
  { type: "button", content: "support" },
  { type: "button", content: "terms" },
  { type: "button", content: "update" },
  { type: "button", content: "welcome" },
  { type: "text", content: "add to cart" },
  { type: "text", content: "click here to continue" },
  { type: "text", content: "confirm your email address" },
  { type: "text", content: "contact us for support" },
  { type: "text", content: "create your account today" },
  { type: "text", content: "dowload the app now" },
  { type: "text", content: "enter your email address" },
  { type: "text", content: "explore our latest features" },
  { type: "text", content: "forgot your password" },
  { type: "text", content: "join our community today" },
  { type: "text", content: "learn more about our services" },
  { type: "text", content: "loading, please wait" },
  { type: "text", content: "new updates are available" },
  { type: "text", content: "password must be at least 8 characters" },
  { type: "text", content: "payment succesful" },
  { type: "text", content: "please fill out all required fields" },
  { type: "text", content: "privacy policy updated" },
  { type: "text", content: "procede to checkout" },
  { type: "text", content: "search results for" },
  { type: "text", content: "sign up for free" },
  { type: "text", content: "something went wrong. please try again" },
  { type: "text", content: "start your free trial now" },
  { type: "text", content: "subscribe to our newletter" },
  { type: "text", content: "terms and conditions apply" },
  { type: "text", content: "thank you for your purchase" },
  { type: "text", content: "view all products" },
  { type: "text", content: "welcome back" },
  { type: "text", content: "we value your feedback" },
  { type: "text", content: "your cart is currently empty" },
  { type: "text", content: "your profile has been updated" }
];
  
